name: Deploy API to Azure App Service

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      # (optional) run tests
      # - name: Test
      #   run: npm test

      - name: Package app
        run: |
          zip -r app.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-zip
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-zip
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: pet-backhend # <-- your App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
